import type { ComponentType } from 'react'
import {
  TextScrambleDemo, SpringDemo, EasingDemo, MasonryDemo, BentoDemo, HamburgerDemo, LightboxDemo,
  AccordionDemo, BadgeChipPillTagDemo, BreadcrumbsDemo, ComboboxDemo, CommandPaletteDemo, DividerDemo,
  DragDropDemo, EmptyStateDemo, FocusVisibleDemo, FormFieldDemo, HoverCardDemo, ModalDrawerSheetDemo,
  PopoverDropdownTooltipDemo, ProgressDemo, ScrimDemo, SkeletonDemo, StickyFixedDemo,
  SwitchCheckboxRadioDemo, TabsDemo, ToastDemo, ToggleGroupDemo, TruncationDemo,
} from './demos-web'
import {
  MacAlertDemo, MacColorWellDemo, MacContextMenuDemo, MacDisclosureDemo, MacDockBadgeDemo,
  MacFocusRingDemo, MacInspectorDemo, MacMenuBarDemo, MacMenuBarExtraDemo, MacPanelDemo,
  MacPopoverDemo, MacPopupPullDownDemo, MacScrollViewDemo, MacSegmentedDemo, MacSheetDemo,
  MacSidebarDemo, MacSliderDemo, MacSplitViewDemo, MacStepperDemo, MacToolbarDemo,
  MacTrafficLightsDemo, MacVibrancyDemo, MacWindowDemo,
} from './demos-macos'
import {
  GlassmorphismDemo, NeubrutalismDemo, FlatDesignDemo, SkeuomorphismDemo, ClaymorphismDemo,
  MinimalismDemo, SwissDemo, WebBrutalismDemo, DarkModeDemo, AuroraDemo, Y2KDemo, PixelDemo,
} from './demos-styles'

export const DEMO_REGISTRY: Record<string, ComponentType> = {
  'text-scramble': TextScrambleDemo,
  'spring-animation': SpringDemo,
  easing: EasingDemo,
  masonry: MasonryDemo,
  'bento-grid': BentoDemo,
  'hamburger-menu': HamburgerDemo,
  lightbox: LightboxDemo,
  accordion: AccordionDemo,
  'badge-chip-pill-tag': BadgeChipPillTagDemo,
  breadcrumbs: BreadcrumbsDemo,
  combobox: ComboboxDemo,
  'command-palette': CommandPaletteDemo,
  'divider-rule': DividerDemo,
  'drag-drop': DragDropDemo,
  'empty-state': EmptyStateDemo,
  'focus-visible': FocusVisibleDemo,
  'form-field': FormFieldDemo,
  'hover-card': HoverCardDemo,
  'modal-drawer-sheet': ModalDrawerSheetDemo,
  'popover-dropdown-tooltip': PopoverDropdownTooltipDemo,
  'progress-indicators': ProgressDemo,
  scrim: ScrimDemo,
  'skeleton-spinner': SkeletonDemo,
  'sticky-fixed': StickyFixedDemo,
  'switch-checkbox-radio': SwitchCheckboxRadioDemo,
  tabs: TabsDemo,
  toast: ToastDemo,
  'toggle-group': ToggleGroupDemo,
  truncation: TruncationDemo,
  'mac-alert': MacAlertDemo,
  'mac-color-well': MacColorWellDemo,
  'mac-context-menu': MacContextMenuDemo,
  'mac-disclosure-triangle': MacDisclosureDemo,
  'mac-dock-badge': MacDockBadgeDemo,
  'mac-focus-ring': MacFocusRingDemo,
  'mac-inspector': MacInspectorDemo,
  'mac-menu-bar': MacMenuBarDemo,
  'mac-menu-bar-extra': MacMenuBarExtraDemo,
  'mac-panel': MacPanelDemo,
  'mac-popover': MacPopoverDemo,
  'mac-popup-pulldown-combo': MacPopupPullDownDemo,
  'mac-scroll-view': MacScrollViewDemo,
  'mac-segmented-control': MacSegmentedDemo,
  'mac-sheet': MacSheetDemo,
  'mac-sidebar': MacSidebarDemo,
  'mac-slider': MacSliderDemo,
  'mac-split-view': MacSplitViewDemo,
  'mac-stepper': MacStepperDemo,
  'mac-toolbar': MacToolbarDemo,
  'mac-traffic-lights': MacTrafficLightsDemo,
  'mac-vibrancy': MacVibrancyDemo,
  'mac-window': MacWindowDemo,
  glassmorphism: GlassmorphismDemo,
  neubrutalism: NeubrutalismDemo,
  'flat-design': FlatDesignDemo,
  skeuomorphism: SkeuomorphismDemo,
  claymorphism: ClaymorphismDemo,
  minimalism: MinimalismDemo,
  swiss: SwissDemo,
  'web-brutalism': WebBrutalismDemo,
  darkmode: DarkModeDemo,
  aurora: AuroraDemo,
  y2k: Y2KDemo,
  pixel: PixelDemo,
}
