import type { ComponentType } from 'react'
import {
  TextScrambleDemo, SpringDemo, EasingDemo, MasonryDemo, BentoDemo, HamburgerDemo, LightboxDemo,
  AccordionDemo, BadgeChipPillTagDemo, BreadcrumbsDemo, ComboboxDemo, CommandPaletteDemo, DividerDemo,
  DragDropDemo, EmptyStateDemo, FocusVisibleDemo, FormFieldDemo, HoverCardDemo, ModalDrawerSheetDemo,
  PopoverDropdownTooltipDemo, ProgressDemo, ScrimDemo, SkeletonDemo, StickyFixedDemo,
  SwitchCheckboxRadioDemo, TabsDemo, ToastDemo, ToggleGroupDemo, TruncationDemo,
  CardGridDemo, SplitScreenDemo, SidebarWebDemo, DashboardDemo, FullBleedDemo, HeroDemo,
  FeatureGridDemo, StickyStorytellingDemo, TimelineDemo, FooterDemo, AnchorLinkDemo,
  MegaMenuDemo, BottomNavDemo, PaginationDemo, BackToTopDemo, CarouselDemo, FabDemo,
  ScrollRevealDemo, ParallaxDemo, ScrollProgressDemo, ScrollSnapDemo, HorizontalScrollDemo,
  InfiniteScrollDemo, MarqueeDemo, HoverMicroDemo, StaggeredDemo, ScrollDrivenDemo,
  LoadingButtonDemo, ErrorStateDemo, RetryStateDemo, OptimisticUiDemo, InlineValidationDemo,
  CustomCursorDemo, MagneticButtonDemo, TiltCardDemo, SpotlightHoverDemo, TextMaskDemo,
  ClipPathRevealDemo, WebGLHeroDemo, ViewTransitionsDemo,
  HoldToConfirmDemo, SwipeActionsDemo, PullToRefreshDemo, BeforeAfterDemo, UndoToastDemo, InlineEditDemo, ScrollShadowDemo, CollapsingHeaderDemo,
  DropzoneDemo, SelectionToolbarDemo, RangeSliderDemo, SortableTableDemo, OverflowToolbarDemo, CharacterCounterDemo, CopyFeedbackDemo, ScrollMinimapDemo,
  OtpInputDemo, ReorderableListDemo, PasswordStrengthDemo, MultiStepFormDemo, NotificationStackDemo, AutosaveDemo, SplitPaneDemo, ColorPickerDemo,
} from './demos-web'
import {
  MacAlertDemo, MacColorWellDemo, MacContextMenuDemo, MacDisclosureDemo, MacDockBadgeDemo,
  MacFocusRingDemo, MacInspectorDemo, MacMenuBarDemo, MacMenuBarExtraDemo, MacPanelDemo,
  MacPopoverDemo, MacPopupPullDownDemo, MacScrollViewDemo, MacSegmentedDemo, MacSheetDemo,
  MacSidebarDemo, MacSliderDemo, MacSplitViewDemo, MacStepperDemo, MacToolbarDemo,
  MacTrafficLightsDemo, MacVibrancyDemo, MacWindowDemo,
} from './demos-macos'
import {
  GlassmorphismDemo, NeubrutalismDemo, FlatDesignDemo, SkeuomorphismDemo, ClaymorphismDemo,
  MinimalismDemo, SwissDemo, WebBrutalismDemo, DarkModeDemo, AuroraDemo, Y2KDemo, PixelDemo,
  EditorialDemo, DuotoneDemo, GradientMeshDemo, GrainDemo, NeumorphismDemo,
} from './demos-styles'

export const DEMO_REGISTRY: Record<string, ComponentType> = {
  'text-scramble': TextScrambleDemo,
  'spring-animation': SpringDemo,
  easing: EasingDemo,
  masonry: MasonryDemo,
  'bento-grid': BentoDemo,
  'hamburger-menu': HamburgerDemo,
  lightbox: LightboxDemo,
  accordion: AccordionDemo,
  'badge-chip-pill-tag': BadgeChipPillTagDemo,
  breadcrumbs: BreadcrumbsDemo,
  combobox: ComboboxDemo,
  'command-palette': CommandPaletteDemo,
  'divider-rule': DividerDemo,
  'drag-drop': DragDropDemo,
  'empty-state': EmptyStateDemo,
  'focus-visible': FocusVisibleDemo,
  'form-field': FormFieldDemo,
  'hover-card': HoverCardDemo,
  'modal-drawer-sheet': ModalDrawerSheetDemo,
  'popover-dropdown-tooltip': PopoverDropdownTooltipDemo,
  'progress-indicators': ProgressDemo,
  scrim: ScrimDemo,
  'skeleton-spinner': SkeletonDemo,
  'sticky-fixed': StickyFixedDemo,
  'switch-checkbox-radio': SwitchCheckboxRadioDemo,
  tabs: TabsDemo,
  toast: ToastDemo,
  'toggle-group': ToggleGroupDemo,
  truncation: TruncationDemo,
  'mac-alert': MacAlertDemo,
  'mac-color-well': MacColorWellDemo,
  'mac-context-menu': MacContextMenuDemo,
  'mac-disclosure-triangle': MacDisclosureDemo,
  'mac-dock-badge': MacDockBadgeDemo,
  'mac-focus-ring': MacFocusRingDemo,
  'mac-inspector': MacInspectorDemo,
  'mac-menu-bar': MacMenuBarDemo,
  'mac-menu-bar-extra': MacMenuBarExtraDemo,
  'mac-panel': MacPanelDemo,
  'mac-popover': MacPopoverDemo,
  'mac-popup-pulldown-combo': MacPopupPullDownDemo,
  'mac-scroll-view': MacScrollViewDemo,
  'mac-segmented-control': MacSegmentedDemo,
  'mac-sheet': MacSheetDemo,
  'mac-sidebar': MacSidebarDemo,
  'mac-slider': MacSliderDemo,
  'mac-split-view': MacSplitViewDemo,
  'mac-stepper': MacStepperDemo,
  'mac-toolbar': MacToolbarDemo,
  'mac-traffic-lights': MacTrafficLightsDemo,
  'mac-vibrancy': MacVibrancyDemo,
  'mac-window': MacWindowDemo,
  glassmorphism: GlassmorphismDemo,
  neubrutalism: NeubrutalismDemo,
  'flat-design': FlatDesignDemo,
  skeuomorphism: SkeuomorphismDemo,
  claymorphism: ClaymorphismDemo,
  minimalism: MinimalismDemo,
  swiss: SwissDemo,
  'web-brutalism': WebBrutalismDemo,
  darkmode: DarkModeDemo,
  aurora: AuroraDemo,
  y2k: Y2KDemo,
  pixel: PixelDemo,
  /* ---------- vocab batch ---------- */
  'card-grid': CardGridDemo,
  'split-screen': SplitScreenDemo,
  'sidebar-web': SidebarWebDemo,
  dashboard: DashboardDemo,
  'full-bleed': FullBleedDemo,
  hero: HeroDemo,
  'feature-grid': FeatureGridDemo,
  'sticky-storytelling': StickyStorytellingDemo,
  timeline: TimelineDemo,
  footer: FooterDemo,
  'anchor-link': AnchorLinkDemo,
  'mega-menu': MegaMenuDemo,
  'bottom-nav': BottomNavDemo,
  pagination: PaginationDemo,
  'back-to-top': BackToTopDemo,
  carousel: CarouselDemo,
  fab: FabDemo,
  'scroll-reveal': ScrollRevealDemo,
  parallax: ParallaxDemo,
  'scroll-progress': ScrollProgressDemo,
  'scroll-snap': ScrollSnapDemo,
  'horizontal-scroll': HorizontalScrollDemo,
  'infinite-scroll': InfiniteScrollDemo,
  marquee: MarqueeDemo,
  'hover-micro': HoverMicroDemo,
  staggered: StaggeredDemo,
  'scroll-driven': ScrollDrivenDemo,
  'loading-button': LoadingButtonDemo,
  'error-state': ErrorStateDemo,
  'retry-state': RetryStateDemo,
  'optimistic-ui': OptimisticUiDemo,
  'inline-validation': InlineValidationDemo,
  'custom-cursor': CustomCursorDemo,
  'magnetic-button': MagneticButtonDemo,
  'tilt-card': TiltCardDemo,
  'spotlight-hover': SpotlightHoverDemo,
  'text-mask': TextMaskDemo,
  'clip-path-reveal': ClipPathRevealDemo,
  'webgl-hero': WebGLHeroDemo,
  'view-transitions': ViewTransitionsDemo,
  'hold-to-confirm': HoldToConfirmDemo,
  'swipe-actions': SwipeActionsDemo,
  'pull-to-refresh': PullToRefreshDemo,
  'before-after': BeforeAfterDemo,
  'undo-toast': UndoToastDemo,
  'inline-edit': InlineEditDemo,
  'scroll-shadow': ScrollShadowDemo,
  'collapsing-header': CollapsingHeaderDemo,
  dropzone: DropzoneDemo,
  'selection-toolbar': SelectionToolbarDemo,
  'range-slider': RangeSliderDemo,
  'sortable-table': SortableTableDemo,
  'overflow-toolbar': OverflowToolbarDemo,
  'character-counter': CharacterCounterDemo,
  'copy-feedback': CopyFeedbackDemo,
  'scroll-minimap': ScrollMinimapDemo,
  'otp-input': OtpInputDemo,
  'reorderable-list': ReorderableListDemo,
  'password-strength': PasswordStrengthDemo,
  'multi-step-form': MultiStepFormDemo,
  'notification-stack': NotificationStackDemo,
  autosave: AutosaveDemo,
  'split-pane': SplitPaneDemo,
  'color-picker': ColorPickerDemo,
  editorial: EditorialDemo,
  duotone: DuotoneDemo,
  'gradient-mesh': GradientMeshDemo,
  grain: GrainDemo,
  neumorphism: NeumorphismDemo,
}
